В данной работе оценивается разность средних чеков на приобретение ПО компаний, получавших техническую поддержку от продавца и не получавших техническую поддержку.

Таким образом можно предположить, стоит ли оказывать тех. поддержку клиентам компании или они в любом случае будут готовы заплатить компании в среднем такую же сумму.

В данных содержится информация о клиентах-компаниях одной из стартап компаний, работающей при поддержке Microsoft. Однако, предположим, что на данный момент нам дана малая выборка - лишь 30 наблюдений (выборка сбалансирована). Первоначальный источник данных: https://www.kaggle.com/datasets/hwwang98/software-usage-promotion-campaign-uplift-model. (К сожалению, данные для быстрой проверки нужной статистики пришлось вставлять ручками, не успеваю разобраться с фильтрацией и обрезкой в питоне, слишком редко в нем работаю, предпочитаю R)

In [11]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
!pip install arch

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.7/981.7 kB 10.9 MB/s eta 0:00:00


In [3]:
from arch.bootstrap import IIDBootstrap, IndependentSamplesBootstrap

Задаем массив данных для компаний, получавших техническую поддержку.

In [6]:
support_false = np.array([17688.363, 14981.43559, 9153.974376, 5760.075096, 11972.18818, 2296.739654, 41743.72206, 9673.221778, 15397.70575, 6321.956387, 2694.216001, 2531.466231, 12387.81871, 9072.07955, 2868.606553])
support_false

array([17688.363   , 14981.43559 ,  9153.974376,  5760.075096,
       11972.18818 ,  2296.739654, 41743.72206 ,  9673.221778,
       15397.70575 ,  6321.956387,  2694.216001,  2531.466231,
       12387.81871 ,  9072.07955 ,  2868.606553])

Задаем массив данных для компаний, не получавших техническую поддержку.

In [7]:
support_true = np.array([32917.13894, 14773.76855, 17098.69823, 17280.70918, 17265.11146, 21953.37179, 50875.56035, 22153.82215, 10063.85753, 10521.9988, 56307.34264, 21267.51393, 27860.93773, 19867.56935, 18647.91666])
support_true

array([32917.13894, 14773.76855, 17098.69823, 17280.70918, 17265.11146,
       21953.37179, 50875.56035, 22153.82215, 10063.85753, 10521.9988 ,
       56307.34264, 21267.51393, 27860.93773, 19867.56935, 18647.91666])

In [9]:
def mean_diff(x, y):
  return np.mean(y) - np.mean(x)

In [10]:
boot_xy = IndependentSamplesBootstrap(support_true, support_false, seed=111111)
boot_xy.conf_int(mean_diff, reps=10000, size=0.95, method='basic')

array([[-20868.89078731],
       [ -4687.94298978]])

Таким образом, становится очевидно, что средний чек компаний, получавших техническую поддержку порядком меньше, чем средний чек компаний, не получавших техническную поддержку.

Можно предположить, что стоит отказаться от предоставления технической поддержки как минимум на безвозмездной основе, так как тех. поддержка не помогает мотивировать клиента на бОльшие затраты.

Однозначно, у этого исследования существуют серьезные ограничения (Кстати, очень бы хотелось увереннее понимать какие именно). Спасибо большое за увлекательную лекцию, теперь я не боюсь бутстрэпа:))